<?php

require_once dirname ( __FILE__ ) . '/../../classes/Yagolands.php';
require_once dirname ( __FILE__ ) . '/../../classes/Config.php';


/**
 * Test class for Config.
 * Generated by PHPUnit on 2011-06-03 at 22:42:31.
 */
class ConfigTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp () {
        $this->object = new Config;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown () {
        
    }

    public static function providerMoltiplicatore () {
        $incrementale = Config::$incrementoDiLivelloPerEdificio;
        $i = 1;
        return array (
            array ( $i, 1 ),
            array ( ++ $i, $incrementale ),
            array ( ++ $i, $incrementale * $incrementale ),
            array ( ++ $i, $incrementale * $incrementale * $incrementale ),
        );

    }

    /**
     * @dataProvider providerMoltiplicatore
     */
    public function testMoltiplicatoreRisorseEdificio ( $a, $b ) {
        $this->assertEquals ( $b, Config::moltiplicatoreRisorseEdificio ( $a ) );

    }

}

?>
